export AUTH0_DOMAIN='fremfi.auth0.com'
export FLASK_ENV='development'
export ALGORITHMS='['RS256']'
export API_AUDIENCE='castingagencyauth'
export DATABASE_URL='postgres://localhost:5432/casting-agency'